### ISSUE TITLE
Is gxx_linux-64 over-pinned?

### ISSUE THREAD

**Issue by apmorton** [conda-forge/cmdstan-feedstock#44]
### Comment:

```
│  ├─ prophet [1.1.4|1.1.5] would require
│  │  └─ cmdstan [2.32.1 |2.33.1 ], which requires
│  │     └─ gxx_linux-64 12.*  but there are no viable options
```

Does this package truly require gcc 12.*, or would anything >= that work?

As it stands it is not possible to use this package in an environment that also uses a newer version of GCC.

**Comment by WardBrian** [comment]
I'm not entirely clear on where that pinning comes from. 

As a source distribution, CmdStan builds on any GCC >= 4.9.3, but because we are pre-compiling certain aspects it may then bake in this requirement

**Comment by apmorton** [comment]
Ah, yes - I just noticed there are .o files being shipped in this package - which means the pin really does need to be this specific (possibly even more specific TBH).

Would it be possible to add variants for all the major gcc versions shipped on conda-forge?

**Comment by WardBrian** [comment]
Maybe? I'd need some help from @conda-forge/help-c-cpp in terms of how such a thing could be set up in the recipe

**Comment by xhochy** [comment]
What is the reason that `*.o` files are shipped in this package?

**Comment by WardBrian** [comment]
Sure. CmdStan is an interface to [Stan](mc-stan.org), which is a programming language for statistical modelling implemented in C++. 

A user writes a Stan file, which gets translated into a C++ class. That class is then compiled and linked into the `main` provided by CmdStan. As such, CmdStan is less "a program you install" as it is "a pile of code and a build system"

This recipe makes sure the end user has a suitable C++ compiler and `make` setup, which is in theory all it would need to do, but it also pre-compiles 
1) some standalone executables provided for downstream analysis of the outputs of Stan programs 
2) some vendored libraries (mainly on Windows, where we can't use conda's own libraries due to ABI concerns) 
3) the `main.o` file in CmdStan. This would be built the first time the user needed it, in theory
